server:
  port: 7001

eureka:
#  #下面server里面的二个是关闭Eureka的自我保护机制
#  #关闭自我保护机制保证服务不可用立马就删除(测试)
#  server:
#    enable-replicated-request-compression: false
#    a-s-g-cache-expiry-timeout-ms: 2000
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责九四维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

